/** User-facing strings, in one place (no bare copy in components). */
export const Copy = {
  AppName: "Tasks",
  UntitledTask: "(untitled)",
  Expand: "Expand",
  Collapse: "Collapse",
  ExpandAll: "Expand all",
  CollapseAll: "Collapse all",
  SearchPlaceholder: "Search tasks…",
  NoSelection: "Select a task to see its details.",
  ToggleTheme: "Toggle theme",
  Back: "Back",
  Close: "Close",
  CopyId: "Copy id",
  CopiedId: "Copied id",
  CopyFailed: "Couldn't copy id",
  SignIn: "Sign in",
  SignInPrompt: "Enter your access token to continue.",
  AccessToken: "Access token",
  InvalidToken: "That token wasn't accepted.",
  RedirectingToSignIn: "Redirecting to sign in…",
  Account: "Account",
  LogOut: "Log out",
  Settings: "Settings",
  ApiKeys: "API keys",
  ApiKeysBlurb: "Tokens for bots, the tasks CLI, and MCP. Each is shown once.",
  Connect: "Connect",
  NewKey: "New key",
  Create: "Create",
  Revoke: "Revoke",
  Revoked: "Revoked",
  KeyLabelPlaceholder: "Label (e.g. ci, claude-web)",
  CopyTokenOnce: "Copy this token now — it won't be shown again.",
  NoKeys: "No API keys yet.",
  LastUsed: "Last used",
  Never: "never",
  Copy: "Copy",
  Copied: "Copied",
  ConnectBlurb: "Connect an AI agent to this board over MCP.",
  McpEndpoint: "MCP endpoint",
  AccountDesc: "Your session on this board.",
  Session: "Session",
  SignedIn: "Signed in",
  OpenAccess: "Open access",
  OpenAccessDesc: "This board is open — no sign-in required.",
  AuthModeLabel: "Auth mode",
  CreateKey: "Create a key",
  YourKeys: "Your keys",
  KeysPageDesc: "Tokens for bots, the tasks CLI, and MCP.",
  ConnectPageDesc: "Give an AI agent access to this board over MCP.",
  Filters: "Filter",
  FilterStatus: "Status",
  FilterType: "Type",
  ChangeType: "Change type",
  ChangeStatus: "Change status",
  ChangePriority: "Change priority",
  Description: "Description",
  AcceptanceCriteria: "Acceptance criteria",
  Design: "Design",
  Notes: "Notes",
  Labels: "Labels",
  Parent: "Parent",
  Children: "Children",
  Blocking: "Blocking",
  // Workspaces
  Personal: "Personal",
  Workspaces: "Workspaces",
  CreateWorkspace: "Create workspace",
  CreateWorkspaceDesc: "New workspaces get their own board and task-id prefix.",
  WorkspaceName: "Workspace name",
  WorkspaceNamePlaceholder: "Acme",
  Cancel: "Cancel",
  Members: "Members",
  MembersDesc: "People with access to this workspace.",
  ManageMembers: "Manage members",
  Workspace: "Workspace",
  Invite: "Invite",
  InviteMember: "Invite member",
  InviteMemberDesc: "They'll get an email to join this workspace.",
  EmailAddress: "Email address",
  EmailPlaceholder: "person@company.com",
  Role: "Role",
  SendInvite: "Send invite",
  PendingInvitations: "Pending invitations",
  Remove: "Remove",
  NoMembers: "No members yet.",
  NoInvitations: "No pending invitations.",
  You: "You",
  WorkspaceSettings: "Workspace settings",
  WorkspaceSettingsDesc: "Rename or leave this workspace.",
  Rename: "Rename",
  Save: "Save",
  DangerZone: "Danger zone",
  LeaveWorkspace: "Leave workspace",
  LeaveWorkspaceDesc: "You'll lose access until you're invited again.",
  DeleteWorkspace: "Delete workspace",
  DeleteWorkspaceDesc: "Permanently removes the workspace for everyone. This cannot be undone.",
  Leave: "Leave",
  Delete: "Delete",
  View: "View",
  ViewAndFilters: "View & filters",
  ViewTree: "Tree",
  ViewGraph: "Graph",
  ViewDashboard: "Dashboard",
  GraphComingSoon: "Graph view is coming soon.",
  Sort: "Sort",
  SortAscending: "Ascending",
  SortDescending: "Descending",
  SortDefault: "Default",
  SortPriority: "Priority",
  SortStatus: "Status",
  SortType: "Type",
  SortTitle: "Title",
  SortId: "ID",
  NoEpics: "No epics to show.",
  NoChildTasks: "No child tasks",
  Done: "done",
} as const;
